services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./portfolio_backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    expose:
      - "9000"
    env_file:
      - ./portfolio_backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "8000:80"
    volumes:
      - ./portfolio_backend:/var/www
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: portfolio_mysql
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_ROOT_PASSWORD: "portfolio9988"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


volumes:
  mysql_data: